const constants = {
	ADD_USER: "ADD_USER",
	ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
	REMOVE_USER: "REMOVE_USER",
	EDIT_USER: "EDIT_USER",

	FETCH_USER: "FETCH_USER",
	CANCEL_FETCHING: "CANCEL_FETCHING",

	ADD_ERROR: "ADD_ERROR",
	CLEAR_ERROR: "CLEAR_ERROR",

	ADD_NOTIFICATION : "ADD_NOTIFICATION",
	REMOVE_NOTIFICATION : "REMOVE_NOTIFICATION",
	
	ADD_USER_DATA: "ADD_USER_DATA",
	ADD_USER_DATA_SUCCESS: "ADD_USER_DATA_SUCCESS",
	REMOVE_USER_DATA: "REMOVE_USER_DATA",
	EDIT_USER_DATA: "EDIT_USER_DATA",
	FETCH_USER_DATA: "FETCH_USER_DATA",

	SHOW_MODAL:"SHOW_MODAL",
	CLOSE_MODAL:"CLOSE_MODAL"
}

export default constants